# Generated by Django 5.1.3 on 2024-11-26 07:51

import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_chunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='chunk',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=pgvector.django.indexes.IvfflatIndex(fields=['embedding'], lists=100, name='embedding_cosine_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
